db.Restaurantes.find({})
db.Restaurantes.find({}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.Restaurantes.find({}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.Restaurantes.find({}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, "address.zipcode": 1 })
db.Restaurantes.find({ borough: "Bronx" })
db.Restaurantes.find({ borough: "Bronx" }).limit(5)
db.Restaurantes.find({ borough: "Bronx" }).skip(5).limit(5)
db.Restaurantes.find({ "grades.score": { $gt: 90 } })
db.Restaurantes.find({ "grades.score": { $gt: 80, $lt: 100 } })
db.Restaurantes.find({ "address.coord": { $lt: -95.754168 } })
db.Restaurantes.find({ cuisine: { $ne: 'American' }, "grades.score": { $gt: 70 }, "address.coord": { $lt: -65.754168 }})
db.Restaurantes.find({ cuisine: { $ne: 'American' }, "grades.score": { $gt: 70 }, "address.coord": { $lt: -65.754168 }})
db.Restaurantes.find({ cuisine: { $ne: 'American' }, "grades.score": { $gt: 70 }, "grades.grade": 'A', borough: { $ne: 'Brooklyn' }}).sort({ cuisine: -1 })
db.Restaurantes.find({ name: /^Wil/ }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.Restaurantes.find({ name: /ces$/ }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.Restaurantes.find({ name: /ces$/ }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.Restaurantes.find({ name: /Reg/ }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.Restaurantes.find({ borough: 'Bronx', $or: [{ cuisine: 'American' }, { cuisine: 'Chinese' }]})
db.Restaurantes.find({ borough: { $in: ['Staten Island', 'Queens', 'Bronx', 'Brooklyn'] }}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.Restaurantes.find({ borough: { $nin: ['Staten Island', 'Queens', 'Bronx', 'Brooklyn'] }}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.Restaurantes.find({ "grades.score": { $not: { $gt: 10 } } }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.Restaurantes.find({ cuisine: { $ne: 'American', $ne: 'Chinese' }, name: { $not: /^Wil/ }, "grades.grade": 'A', "grades.score": 11, "grades.date": ISODate("2014-08-11T00:00:00Z")}, { restaurant_id: 1,  name: 1, borough: 1, cuisine: 1 })
db.Restaurantes.find({ "grades.1.grade": 'A', "grades.1.score": 9, "grades.1.date": ISODate("2014-08-11T00:00:00Z")}, { restaurant_id: 1, name: 1, grades: 1 })
db.Restaurantes.find({ "address.coord.1": { $gt: 42, $lte: 52 }}, { restaurant_id: 1, name: 1, "address.coord": 1 })
db.Restaurantes.find().sort({ name: 1 })
db.Restaurantes.find().sort({ name: -1 })
db.Restaurantes.find().sort({ cuisine: 1, borough: -1 })
db.Restaurantes.find({ "address.street": { $not: /calle/ } }, { "address.street": 1 })
db.Restaurantes.find({ "address.coord": { $type: "double" } })
db.Restaurantes.find({ "grades.score": { $mod: [7, 0] } }, { restaurant_id: 1, name: 1, "grades.grade": 1 })
db.Restaurantes.find({ name: /mon/ }, { name: 1, borough: 1, "address.coord": 1, cuisine: 1 })
db.Restaurantes.find({ name: /^Mad/ }, { name: 1, borough: 1, "address.coord": 1, cuisine: 1 })
